---
title: "MAJIQ analysis sample size endodermall cell vs H1 cell line"
author: "Annika Ladwig"
output:
  prettydoc::html_pretty:
    theme: architect
---

```{r, echo=FALSE, warning=FALSE,message=FALSE,error=FALSE,fig.keep='all'}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE,error=FALSE,fig.keep='all'}

# LIBRARIES 
library(dplyr)
library(ggplot2)
library(stringr)
library(ggpubr)
library("RColorBrewer")
library("ggVennDiagram")
library("wesanderson")
library(ggrastr)
library("colorspace")
#library(ggecdf)
library(UpSetR)
library(halfmoon)

# MY PARMETERS
probabilityThreshold = 0.9

# MY THEME
source("C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/theme_paper.R")
theme_set(theme_paper())

# MY FUNCTIONS
# function to load files as data frames
loadFiles <- function(x){
  x = read.table(file = x,
                 header = TRUE,
                 sep = "\t",
                 stringsAsFactors = FALSE)
}

# function to count semicolons of column "mean_dpsi_per_lsv_junction"
# to find out the number of junctions per LSV
# store this information in new column "nJunctions"
countJunctions <- function(x) {
    junctionsPerLSV = x$mean_dpsi_per_lsv_junction %>%
   str_count(pattern = ";") + 1
  x$nJunctions = junctionsPerLSV
  x
}

# count the amount of LSVs with 2, 3, 4, ... junctions
# create data frame with this information
complexityLSVs <- function(x) {
   junctionsPerLSV = x$nJunctions %>%
    table(dnn="junctionsPerLSV") %>%
    as.data.frame
   junctionsPerLSV
}

# function to extract max dpsi for each LSV and add new column with this information
extractMaxDPSIs <- function(x) {
  maxDeltaPSIs = x$mean_dpsi_per_lsv_junction %>%
    str_split(pattern = ";") %>%
    sapply(FUN = function(dPSIs){
      return(
        dPSIs %>% as.numeric %>% abs %>% max
      )
    })
  x$maxDeltaPSI = maxDeltaPSIs
  x
}

# function extract max prob. for each LSV and add a new column with this information
extractMaxProbs <- function(x) {
  maxProbs = x$probability_changing %>%
    str_split(pattern=";") %>%
    sapply(FUN=function(probs){
      return(
        probs %>% as.numeric %>% max
      )
    })
  x$maxProb = maxProbs
  x
}
```

```{r, echo=FALSE, warning=FALSE,message=FALSE,error=FALSE,fig.keep='all'}
# LOAD FILE SETS (read length 100 nt)

# 2 samples
# load voila files as list
two_samples_Dir = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/endodermal_cell_vs_H1_cell_line/MAJIQ/2_samples/"

two_samples_files = list.files(path = two_samples_Dir, pattern = ".tsv")
setwd(two_samples_Dir)

# load dpsi tsv files as data frames
# & name list elements
two_samples_dfs = lapply(two_samples_files, loadFiles)
names(two_samples_dfs) = c("sample_1_2", "sample_1_3", "sample_2_3")


# 3 samples
# load voila files as list
three_samples_Dir = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/endodermal_cell_vs_H1_cell_line/MAJIQ/3_samples"

three_samples_files = list.files(path = three_samples_Dir, pattern = ".tsv")
setwd(three_samples_Dir)

# load dpsi tsv files as data frames
# & name list elements
three_samples_dfs = lapply(three_samples_files, loadFiles)
names(three_samples_dfs) = c("sample_1_2_3")
```

# Influence on LSV detection
```{r}
# put all sample variations in one list
sample_sizes_df = append(two_samples_dfs, list(three_samples_dfs$sample_1_2_3))

two_samples_dfs[1]

# detected LSVs
nLSVs_sample_1_2 = nrow(sample_sizes_df[[1]])
nLSVs_sample_1_3 = nrow(sample_sizes_df[[2]])
nLSVs_sample_2_3 = nrow(sample_sizes_df[[3]])
nLSVs_sample_1_2_3 = nrow(sample_sizes_df[[4]])

cat("two samples", fill = TRUE)
nLSVs_sample_1_2
nLSVs_sample_1_3
nLSVs_sample_2_3

cat("three samples", fill = TRUE)
nLSVs_sample_1_2_3

# create dataframe with nLSVs 
nLSVs_df = data.frame(nSamples=c("2", "2", "2", "3"),
                      nLSVs=c(nLSVs_sample_1_2, nLSVs_sample_1_3, nLSVs_sample_2_3, nLSVs_sample_1_2_3))

# number of LSVs bar chart
nLSVs_sampleSize = ggplot(nLSVs_df, aes(nSamples, y = nLSVs))+
  stat_summary(fun = "mean",
               geom = "bar",
               size = 0.5,
               show.legend = FALSE,
               mapping = aes(fill=nSamples)) +
  scale_fill_manual(name = "", values = c("#EFC4E4", "#D065B5")) +
  ylim(0, 50500) +
  geom_point(alpha = 0.6, color = darken("#EFC4E4", 0.25)) +
  xlab("read length [nt]") +
  ylab("# nLSVs") +
  ggtitle("D") +
  scale_x_discrete(labels = c("75", "100")) +
  geom_text(aes(label=nLSVs), position=position_dodge(width=0.9), vjust=1)

nLSVs_sampleSize

# save ggplots
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/nLSVs_sampleSize.pdf", plot = nLSVs_sampleSize, width = 2.46, height = 6, units = "cm")
```
# Influence on LSV complexity
```{r}
# create new list with the data frames that contain the information about the complexity of the LSVs
sample_sizes_df = lapply(sample_sizes_df, countJunctions)
sample_sizes_complexityLSVs = lapply(sample_sizes_df, complexityLSVs)

# add new column for number of samples to differ the data later
# when merging single data frames to one
sample_sizes_complexityLSVs[[4]]$n_samples = "3"

# build mean data frame out of data frames for 2 samples 
junctionsPerLSV = sample_sizes_complexityLSVs[[1]]$junctionsPerLSV
Freq = c()
for (i in 1:22){
  Freq = append(Freq, mean(c(sample_sizes_complexityLSVs[[1]]$Freq[i], sample_sizes_complexityLSVs[[2]]$Freq[i], sample_sizes_complexityLSVs[[3]]$Freq[i])))
}
two_samples_complexityLSVs = data.frame(junctionsPerLSV = junctionsPerLSV, 
                                        Freq = Freq,
                                        n_samples = 2)

# create data frame out of all sample sizes to build a stacked bar chart
nJunctions_df = rbind(two_samples_complexityLSVs, sample_sizes_complexityLSVs[[4]]) 

# all LSVs with junctions > 4 are grouped into one category
# so that all LSVs with > 4 junctions get the same color in following stacked bar chart
for (i in 1:nrow(nJunctions_df)){
  if (as.integer(nJunctions_df[i, "junctionsPerLSV"]) >= 5) {
    nJunctions_df[i, "junctionsPerLSV"] = factor(5)
  }
}

# stacked bar chart to show complexity of LSVs for each sample size
# source: http://jessicacorman.weebly.com/news--musings/how-to-make-a-stacked-bar-chart-with-color-shading
StackedBarChart_nJunctions = ggplot(nJunctions_df, aes(x = n_samples, y = Freq)) +
  geom_bar(stat = "identity", aes(fill = n_samples), position = "fill", show.legend = FALSE) +
  scale_fill_manual(values = c("#EFC4E4", "#C76EB1"),
                    labels = c("2", "3"),
                    name = "# samples") + 
  geom_bar(stat = "identity", fill = "black", aes(alpha = junctionsPerLSV), position = "fill", show.legend = FALSE) +
  scale_alpha_manual(values = c(0, 0.3, 0.55, 0.8),
                     name = "junctions per LSV", 
                     breaks = c("2", "3", "4", "5"),
                     labels = c("2", "3", "4", "> 4")) +
  scale_x_discrete(labels = c("2", "3")) +
  xlab("#samples") +
  ylab("fraction LSVs [%]") +
  ggtitle("B") 

StackedBarChart_nJunctions

# save ggplots
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/complexityLSVs_sampleSize.pdf", plot = StackedBarChart_nJunctions, width = 2.26, height = 6, units = "cm")
```
# Influence on significance of LSVs
```{r}
# extract max dpsi for each LSV and add new column with this information
sample_sizes_df = lapply(sample_sizes_df, extractMaxDPSIs)

# extract max prob. for each LSV and add a new column with this information
sample_sizes_df = lapply(sample_sizes_df, extractMaxProbs)

# add new column called "significant" for each sample combination which could be TRUE/FALSE 
# TRUE if maxProb >= 0.9 and maxDPSI >= 0.05
sample_sizes_df[[1]]$significant = sample_sizes_df[[1]]$maxProb >= probabilityThreshold & sample_sizes_df[[1]]$maxDeltaPSI >= 0.05
sample_sizes_df[[2]]$significant = sample_sizes_df[[2]]$maxProb >= probabilityThreshold & sample_sizes_df[[2]]$maxDeltaPSI >= 0.05
sample_sizes_df[[3]]$significant = sample_sizes_df[[3]]$maxProb >= probabilityThreshold & sample_sizes_df[[3]]$maxDeltaPSI >= 0.05
sample_sizes_df[[4]]$significant = sample_sizes_df[[4]]$maxProb >= probabilityThreshold & sample_sizes_df[[4]]$maxDeltaPSI >= 0.05


# output which LSVs are significant and which are not for sample size combination
table(sample_sizes_df[[1]]$significant)
table(sample_sizes_df[[2]]$significant)
table(sample_sizes_df[[3]]$significant)
table(sample_sizes_df[[4]]$significant)

# count significant and not significant LSVs for each sample combination
nSignificant_1_2 = sum(sample_sizes_df[[1]]$significant)
nNotSignificant_1_2 = (nLSVs_sample_1_2-sum(sample_sizes_df[[1]]$significant))
nSignificant_1_3 = sum(sample_sizes_df[[2]]$significant)
nNotSignificant_1_3 = (nLSVs_sample_1_3-sum(sample_sizes_df[[2]]$significant))
nSignificant_2_3 = sum(sample_sizes_df[[3]]$significant)
nNotSignificant_2_3 = (nLSVs_sample_2_3-sum(sample_sizes_df[[3]]$significant))
nSignificant_1_2_3 = sum(sample_sizes_df[[4]]$significant)
nNotSignificant_1_2_3 = (nLSVs_sample_1_2_3-sum(sample_sizes_df[[4]]$significant))

# calculate mean of regulated LSVs for sample size of 2
mean_regulated_2_samples = round(mean(c(nSignificant_1_2, nSignificant_1_3, nSignificant_2_3)))
mean_nLSVs_2_samples = round(mean(nLSVs_sample_1_2, nLSVs_sample_1_3, nLSVs_sample_2_3))
mean_notRegulated_2_samples =mean_nLSVs_2_samples - mean_regulated_2_samples

# create data frame with a column for the read length
# and a column indicating whether the associated LSV is significant or not 
nSignificantLSVs_df_relative = data.frame(comparison=c(rep("012", nrow(sample_sizes_df[[1]])),
                                                   rep("013", nrow(sample_sizes_df[[2]])), 
                                                   rep("023", nrow(sample_sizes_df[[3]])), 
                                                   rep("123", nrow(sample_sizes_df[[4]]))),
                                      significant=c(sample_sizes_df[[1]]$significant,
                                                    sample_sizes_df[[2]]$significant, 
                                                    sample_sizes_df[[3]]$significant, 
                                                    sample_sizes_df[[4]]$significant))

nSignificantLSVs_df_relative = data.frame(comparison=rep(c("2", "3"), each = 2),
                                          significant=c("TRUE 2", "FALSE", "TRUE 3", "FALSE"),
                                          n=c(mean_regulated_2_samples, mean_nLSVs_2_samples, 
                                              sum(sample_sizes_df[[4]]$significant), nrow(sample_sizes_df[[4]])))
nSignificantLSVs_df_relative

specie <- c(rep("sorgho" , 3) , rep("poacee" , 3) , rep("banana" , 3) , rep("triticum" , 3) )
condition <- rep(c("normal" , "stress" , "Nitrogen") , 4)
value <- abs(rnorm(12 , 0 , 15))
data <- data.frame(specie,condition,value)
data


'# differ between the significance of LSVs of different sample combinations to plot them in different colors 
for (i in 1:nrow(nSignificantLSVs_df_relative)){
  if (nSignificantLSVs_df_relative[i, "comparison"] == "0 1 2" && nSignificantLSVs_df_relative[i, "significant"] == TRUE){
    nSignificantLSVs_df_relative[i, "significant"] = "TRUE 2 samples"
  }
  if (nSignificantLSVs_df_relative[i, "comparison"] == "0 1 3" && nSignificantLSVs_df_relative[i, "significant"] == TRUE){
    nSignificantLSVs_df_relative[i, "significant"] = "TRUE 2 samples"
  }
  if (nSignificantLSVs_df_relative[i, "comparison"] == "0 2 3" && nSignificantLSVs_df_relative[i, "significant"] == TRUE){
    nSignificantLSVs_df_relative[i, "significant"] = "TRUE 2 samples"
  }
  if (nSignificantLSVs_df_relative[i, "comparison"] == "1 2 3" && nSignificantLSVs_df_relative[i, "significant"] == TRUE){
    nSignificantLSVs_df_relative[i, "significant"] = "TRUE 3 samples"
  }
}'

# percentage stacked bar chart
# stacked bar chart showing fraction of significant LSVs among all LSVs for each read length   
nSignificantLSVs_bar_relative = ggplot(nSignificantLSVs_df_relative, aes(x = comparison, y = n, fill = significant)) +
  geom_bar(position = "fill", stat = "identity", show.legend = FALSE) +
  xlab("# samples") +
  ylab("fraction LSVs [%]") +
  coord_cartesian(ylim = c(0, 0.02)) +
  scale_fill_manual(name= "significant", values = c("lightgrey", "#EFC4E4", "#D065B5"), labels = c("FALSE", "TRUE")) +
  ggtitle("A") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))

nSignificantLSVs_bar_relative


# bar chart with absolute number of significant LSVs
# create dataframe with significant nLSVs 
nSignificantLSVs_df_absolute = data.frame(nSamples=c("2", "2", "2", "3"),
                      nSignificantLSVs=c(nSignificant_1_2, nSignificant_1_3, nSignificant_2_3, nSignificant_1_2_3))

nSignificantLSVs_bar_absolute = ggplot(nSignificantLSVs_df_absolute, aes(nSamples, nSignificantLSVs))+
  stat_summary(fun = "mean",
               geom = "bar",
               size = 0.5,
               show.legend = FALSE,
               mapping = aes(fill=nSamples)) +
  scale_fill_manual(name = "", values = c("#EFC4E4", "#D065B5")) +
  geom_point(alpha = 0.6, color = darken("#EFC4E4", 0.25)) +
  xlab("# samples") +
  ylab("# significant LSVs") +
  ggtitle("C") +
  geom_text(aes(label=nSignificantLSVs), position=position_dodge(width=0.9), vjust=1)
  
nSignificantLSVs_bar_absolute


# save plots
ggsave(filename = "nSignficantLSVs_sample_size_absolute.pdf", plot = nSignificantLSVs_bar_absolute, width = 2.2, height = 6, units = "cm", path = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots")
ggsave(filename = "nSignficantLSVs_sample_size_relative.pdf", plot = nSignificantLSVs_bar_relative, width = 2.41, height = 6, units = "cm", path = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots")
```

## Shared significant regulated LSVs between the different sample sizes
```{r}
# check number of regulated LSVs
# TRUE = 1, FALSE = 0
sum(sample_sizes_df[[1]]$significant)
sum(sample_sizes_df[[2]]$significant)
sum(sample_sizes_df[[3]]$significant)
sum(sample_sizes_df[[4]]$significant)

# extract all significant LSVs for each read length
significantLSVs_samples_12 = sample_sizes_df[[1]]$lsv_id[sample_sizes_df[[1]]$significant == TRUE]

significantLSVs_samples_13 = sample_sizes_df[[2]]$lsv_id[sample_sizes_df[[2]]$significant == TRUE]

significantLSVs_samples_23 = sample_sizes_df[[3]]$lsv_id[sample_sizes_df[[3]]$significant == TRUE]

significantLSVs_samples_123 = sample_sizes_df[[4]]$lsv_id[sample_sizes_df[[4]]$significant == TRUE]

significantLSVs_all = list("012" = c(significantLSVs_samples_12), "013" = c(significantLSVs_samples_13), "023" = c(significantLSVs_samples_23), "123" = c(significantLSVs_samples_123))

'# create list with all significant LSVs for each read length
U2AF2_significantLSVs_all = list("36" = c(U2AF2_significantLSVs_36), "50" = c(U2AF2_significantLSVs_50), "75" = c(U2AF2_significantLSVs_75), "100" = c(U2AF2_significantLSVs_100))

significantLSVs_all_df = fromList(significantLSVs_all)
significantLSVs_all_df
upset(fromList(significantLSVs_all), order.by = "freq", sets.bar.color = c(lighten("slateblue1", 0.5), darken("slateblue4", 0.3), lighten("slateblue1", 0.5), lighten("slateblue1", 0.5))) '

# upset plot
pdf(file="C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/upset_sample_size.pdf", width=3.6, height=3) 
# make upset plot from this information
upset(fromList(significantLSVs_all), 
      order.by = "freq", 
      sets.bar.color = c("#EFC4E4", "#EFC4E4", "#EFC4E4", "#D065B5"), 
      sets.x.label = "# LSVs", 
      mainbar.y.label = "# shared significant LSVs")
dev.off()
```

```{r}
'# plot the max. dpsi against the max. probability for each LSV 
significantDeltaPSI_scatter = ggarrange(
  
  ggplot(sample_sizes_df[[1]], aes(x = maxDeltaPSI, y = maxProb)) +
    ggrastr::geom_point_rast(alpha = .25, color = "blue") +
    geom_hline(yintercept = probabilityThreshold, col = "red3", linetype = "dashed", size = 0.3) +
    geom_vline(xintercept = 0.05, col = "red3", linetype = "dashed", size = 0.3) +
    coord_cartesian(xlim = c(NA, 1)) +
    xlab("delta psi") +
    ylab("probability changing") +
    facet_wrap(~"samples 1 2"),
  
  ggplot(sample_sizes_df[[2]], aes(x = maxDeltaPSI, y = maxProb)) +
    ggrastr::geom_point_rast(alpha = .25, color = "lightblue") +
    geom_hline(yintercept = probabilityThreshold, col = "red3", linetype = "dashed", size = 0.3) +
    geom_vline(xintercept = 0.05, col = "red3", linetype = "dashed", size = 0.3) +
    coord_cartesian(xlim = c(NA, 1)) +
    xlab("delta psi") +
    ylab("probability changing") +
    facet_wrap(~"samples 1 3"),
  
 ggplot(sample_sizes_df[[3]], aes(x = maxDeltaPSI, y = maxProb)) +
    ggrastr::geom_point_rast(alpha = .25, color = "lightblue") +
    geom_hline(yintercept = probabilityThreshold, col = "red3", linetype = "dashed", size = 0.3) +
    geom_vline(xintercept = 0.05, col = "red3", linetype = "dashed", size = 0.3) +
    coord_cartesian(xlim = c(NA, 1)) +
    xlab("delta psi") +
    ylab("probability changing") +
    facet_wrap(~"samples 2 3"),
  
  ggplot(sample_sizes_df[[4]], aes(x = maxDeltaPSI, y = maxProb)) +
    ggrastr::geom_point_rast(alpha = .25, color = "dodgerblue4") +
    geom_hline(yintercept = probabilityThreshold, col = "red3", linetype = "dashed", size = 0.3) +
    geom_vline(xintercept = 0.05, col = "red3", linetype = "dashed", size = 0.3) +
    coord_cartesian(xlim = c(NA, 1)) +
    xlab("delta psi") +
    ylab("probability changing") +
    facet_wrap(~"samples 1 2 3"),
  
  
  nrow = 2, ncol = 2
)

significantDeltaPSI_scatter = annotate_figure(significantDeltaPSI_scatter, top = text_grob("Significance of splicing changes", size = 16, just = "centre", face = "bold"))

significantDeltaPSI_scatter'
```

# Influence on teh size of the detected splicing changes
```{r}

# ecdf for delta psis and p values

ecdf_deltaPSI = ggplot() +
  stat_ecdf(aes(x = maxDeltaPSI), data = sample_sizes_df[[1]], geom = "line", color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxDeltaPSI, color = "0 1 2"), data = sample_sizes_df[[1]], geom = "line", size = 1, pad=FALSE) +
  stat_ecdf(aes(x = maxDeltaPSI), data = sample_sizes_df[[2]], geom = "line", color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxDeltaPSI, color = "0 1 3"), data = sample_sizes_df[[2]], geom = "line", size = 1, pad=FALSE) +
  stat_ecdf(aes(x = maxDeltaPSI), data = sample_sizes_df[[3]], geom = "line", color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxDeltaPSI, color = "0 2 3"), data = sample_sizes_df[[3]], geom = "line", size = 1, pad=FALSE) +
  stat_ecdf(aes(x = maxDeltaPSI), data = sample_sizes_df[[4]], geom = "line", color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxDeltaPSI, color = "1 2 3"), data = sample_sizes_df[[4]], geom = "line", size = 1, pad=FALSE) +
  scale_color_manual(values = c("0 1 2" = "#EFC4E4", "0 1 3" = "#EFC4E4", "0 2 3" = "#EFC4E4", "1 2 3" = "#C76EB1"), 
                     name = "samples", 
                     labels = c("1 2", "1 3", "2 3", "1 2 3")) + 
  coord_cartesian(xlim=c(0, 0.5)) +
  geom_vline(xintercept = 0.05, col = "red3", linetype = "dashed", size = 0.5) +
  ylab("ecdf") +
  xlab("dPSI") +
  ggtitle("C") +
  theme(legend.position="none")

ecdf_probChanging = ggplot() +
  stat_ecdf(aes(x = maxProb), data = sample_sizes_df[[1]], geom = "line", color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxProb, color = "0 1 2"), data = sample_sizes_df[[1]], size = 1, geom = "line", pad=FALSE) +
  
  stat_ecdf(aes(x = maxProb), data = sample_sizes_df[[2]], color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxProb, color = "0 1 3"), data = sample_sizes_df[[2]], size = 1, pad=FALSE) +
  
  stat_ecdf(aes(x = maxProb), data = sample_sizes_df[[3]], color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxProb, color = "0 2 3"), data = sample_sizes_df[[3]], size = 1, geom = "line", pad=FALSE) +
  
  stat_ecdf(aes(x = maxProb), data = sample_sizes_df[[4]], color="black", size = 1.25, pad=FALSE) +
  stat_ecdf(aes(x = maxProb, color = "1 2 3"), data = sample_sizes_df[[4]], size = 1, geom = "line", pad=FALSE) +
  
  scale_color_manual(values = c("0 1 2" = "#EFC4E4", "0 1 3" = "#EFC4E4", "0 2 3" = "#EFC4E4", "1 2 3" = "#C76EB1"), 
                     name = "samples", 
                     labels = c("1 2", "1 3", "2 3", "1 2 3")) + 
  geom_vline(xintercept = 0.05, col = "red3", linetype = "dashed", size = 0.5) +
  ylab("ecdf") +
  xlab("probability changing") +
  ggtitle("C")  +
  theme(legend.position="none")


ecdf_deltaPSI
ecdf_probChanging

# save ggplots
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/ecdf_dPSI_sampleSize.pdf", plot = ecdf_deltaPSI, width = 4.2, height = 4.2, units = "cm")

ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/ecdf_probChanging_sampleSize.pdf", plot = ecdf_probChanging, width = 4.2, height = 4.2, units = "cm")
```

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,fig.keep='all'}

sample_sizes_df[[1]]$samples = "0 1 2"
sample_sizes_df[[2]]$samples = "0 1 3"
sample_sizes_df[[3]]$samples = "0 2 3"
sample_sizes_df[[4]]$samples = "1 2 3"

# histograms of dPSIs for each sample combination
ggarrange(
  ggplot(data=sample_sizes_df[[1]], aes(x=maxDeltaPSI, y = ..density..)) +
    geom_histogram(binwidth=.025, fill="#EFC4E4", color="black") +
    #coord_cartesian(xlim = c(0.05, 0.3), ylim = c(0, 5)) +
    #coord_cartesian(xlim = c(0, 0.3), ylim = c(0, 40000)) +
    xlab("\u0394\u03A8") +
    ylab("fraction [%]") +
    ggtitle("sample 1 2"),
  
  ggplot(data=sample_sizes_df[[2]], aes(x=maxDeltaPSI, y = ..density..)) +
    geom_histogram(binwidth=.025, fill="#EFC4E4", color="black") +
    #coord_cartesian(xlim = c(0.05, 0.3), ylim = c(0, 5)) +
    #coord_cartesian(xlim=c(0, 0.3), ylim = c(0, 40000)) +
    xlab("\u0394\u03A8") +
    ylab("fraction [%]") +
    ggtitle("sample 1 3"),
  
  ggplot(data=sample_sizes_df[[3]], aes(x=maxDeltaPSI, y = ..density..)) +
    geom_histogram(binwidth=.025, fill="#EFC4E4", color="black") +
    #coord_cartesian(xlim = c(0.05, 0.3), ylim = c(0, 5)) +
    #coord_cartesian(xlim=c(0, 0.3), ylim = c(0, 40000)) +
    xlab("\u0394\u03A8") +
    ylab("fraction [%]") +
    ggtitle("sample 2 3"),
  
  ggplot(data=sample_sizes_df[[4]], aes(x=maxDeltaPSI, y = ..density..)) +
    geom_histogram(binwidth=.025, fill="#C76EB1", color="black") +
    #coord_cartesian(xlim = c(0.05, 0.3), ylim = c(0, 5)) +
    #coord_cartesian(xlim=c(0, 0.3), ylim = c(0, 40000)) +
    xlab("\u0394\u03A8") +
    ylab("fraction [%]") +
    ggtitle("sample 1 2 3"),
  
  ncol=2, nrow=2
)

# all histograms in one
ggplot(data=NULL, aes(x=maxDeltaPSI, y = ..density..)) +
    geom_histogram(data=sample_sizes_df[[1]], binwidth=.025, fill="#EFC4E4", color="black", alpha=0.5) +
    geom_histogram(data=sample_sizes_df[[2]], binwidth=.025, fill="#EFC4E4", color="black", alpha=0.5) +
    geom_histogram(data=sample_sizes_df[[3]], binwidth=.025, fill="#EFC4E4", color="black", alpha=0.5) +
    geom_histogram(data=sample_sizes_df[[4]], binwidth=.025, fill="blue", color="black", alpha=0.5) +
    coord_cartesian(xlim = c(0.2, 0.5), ylim = c(0, 0.1)) +
    xlab("\u0394\u03A8") +
    ylab("fraction [%]") +
    ggtitle("normalised histogram for all sample combinations") 
  
```

## Shared binary regulation between the different number of samples
# ALL BINARY LSVs
```{r, warning=FALSE,message=FALSE,error=FALSE,fig.keep='all'}

# ALL BINARY LSVs
# --------------------------------------------------------------------------------------------------------------------------------------

# filter the data frames for significant LSVs with 2 Junctions
filtered_samples_12 = sample_sizes_df[[1]][sample_sizes_df[[1]]$nJunctions == 2,]

filtered_samples_13 = sample_sizes_df[[2]][sample_sizes_df[[2]]$nJunctions == 2,]

filtered_samples_23 = sample_sizes_df[[3]][sample_sizes_df[[3]]$nJunctions == 2,]

filtered_samples_123 = sample_sizes_df[[4]][sample_sizes_df[[4]]$nJunctions == 2,]


# identify shared significant LSVs for each comparison
# comparison 100/75, 100/50, 100/36
shared_samples_12_13 = intersect(filtered_samples_12$lsv_id, filtered_samples_13$lsv_id) 
length(shared_samples_12_13)

shared_samples_12_23 = intersect(filtered_samples_12$lsv_id, filtered_samples_23$lsv_id) 
length(shared_samples_12_23)

shared_samples_12_123 = intersect(filtered_samples_12$lsv_id, filtered_samples_123$lsv_id) 
length(shared_samples_12_123)

shared_samples_13_23 = intersect(filtered_samples_13$lsv_id, filtered_samples_23$lsv_id) 
length(shared_samples_13_23)

shared_samples_13_123 = intersect(filtered_samples_13$lsv_id, filtered_samples_123$lsv_id) 
length(shared_samples_13_123)

shared_samples_23_123 = intersect(filtered_samples_23$lsv_id, filtered_samples_123$lsv_id) 
length(shared_samples_23_123)


# extract filtered LSVs from the data frames above
# compare samples 1 & 2 with 1 & 3
match_samples_12_13 <- filtered_samples_12[match(shared_samples_12_13, filtered_samples_12$lsv_id),]

match_samples_13_12 <- filtered_samples_13[match(shared_samples_12_13, filtered_samples_13$lsv_id),]

# compare samples 1 & 2 with 2 & 3
match_samples_12_23 <- filtered_samples_12[match(shared_samples_12_23, filtered_samples_12$lsv_id),]

match_samples_23_12 <- filtered_samples_23[match(shared_samples_12_23, filtered_samples_23$lsv_id),]

# compare samples 1 & 2 with 1 & 2 & 3
match_samples_12_123 <- filtered_samples_12[match(shared_samples_12_123, filtered_samples_12$lsv_id),]

match_samples_123_12 <- filtered_samples_123[match(shared_samples_12_123, filtered_samples_123$lsv_id),]

# compare samples 1 & 3 with 2 & 3
match_samples_13_23 <- filtered_samples_13[match(shared_samples_13_23, filtered_samples_13$lsv_id),]

match_samples_23_13 <- filtered_samples_23[match(shared_samples_13_23, filtered_samples_23$lsv_id),]

# compare samples 1 & 3 with 1 & 2 & 3
match_samples_13_123 <- filtered_samples_13[match(shared_samples_13_123, filtered_samples_13$lsv_id),]

match_samples_123_13 <- filtered_samples_123[match(shared_samples_13_123, filtered_samples_123$lsv_id),]

# compare samples 2 & 3 with 1 & 2 & 3
match_samples_23_123 <- filtered_samples_23[match(shared_samples_23_123, filtered_samples_23$lsv_id),]

match_samples_123_23 <- filtered_samples_123[match(shared_samples_23_123, filtered_samples_123$lsv_id),]


# extract dpsi value of the first junction for all LSVs
# deltapsi samples 1 & 2 vs samples 1 & 3
deltaPSI_samples_12_vs_13 = match_samples_12_13$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_13_vs_12 = match_samples_13_12$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 2 vs samples 2 & 3
deltaPSI_samples_12_vs_23 = match_samples_12_23$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_23_vs_12 = match_samples_23_12$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 2 vs samples 1 & 2 & 3
deltaPSI_samples_12_vs_123 = match_samples_12_123$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_123_vs_12 = match_samples_123_12$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 3 vs samples 2 & 3
deltaPSI_samples_13_vs_23 = match_samples_13_23$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_23_vs_13 = match_samples_23_13$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 3 vs samples 1 & 2 & 3
deltaPSI_samples_13_vs_123 = match_samples_13_123$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_123_vs_13 = match_samples_123_13$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 2 & 3 vs samples 1 & 2 & 3
deltaPSI_samples_23_vs_123 = match_samples_23_123$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_123_vs_23 = match_samples_123_23$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric


# SIGNIFICANT BINARY LSVs
# --------------------------------------------------------------------------------------------------------------------------------------

# filter the data frames for significant LSVs with 2 Junctions
filtered_samples_12_sig = sample_sizes_df[[1]][sample_sizes_df[[1]]$nJunctions == 2 & sample_sizes_df[[1]]$significant == TRUE,]

filtered_samples_13_sig = sample_sizes_df[[2]][sample_sizes_df[[2]]$nJunctions == 2 & sample_sizes_df[[2]]$significant == TRUE,]

filtered_samples_23_sig = sample_sizes_df[[3]][sample_sizes_df[[3]]$nJunctions == 2 & sample_sizes_df[[3]]$significant == TRUE,]

filtered_samples_123_sig = sample_sizes_df[[4]][sample_sizes_df[[4]]$nJunctions == 2 & sample_sizes_df[[4]]$significant == TRUE,]


# identify shared significant LSVs for each comparison
# comparison 100/75, 100/50, 100/36
shared_samples_12_13_sig = intersect(filtered_samples_12_sig$lsv_id, filtered_samples_13_sig$lsv_id) 
length(shared_samples_12_13_sig)

shared_samples_12_23_sig = intersect(filtered_samples_12_sig$lsv_id, filtered_samples_23_sig$lsv_id) 
length(shared_samples_12_23_sig)

shared_samples_12_123_sig = intersect(filtered_samples_12_sig$lsv_id, filtered_samples_123_sig$lsv_id) 
length(shared_samples_12_123_sig)

shared_samples_13_23_sig = intersect(filtered_samples_13_sig$lsv_id, filtered_samples_23_sig$lsv_id) 
length(shared_samples_13_23_sig)

shared_samples_13_123_sig = intersect(filtered_samples_13_sig$lsv_id, filtered_samples_123_sig$lsv_id) 
length(shared_samples_13_123_sig)

shared_samples_23_123_sig = intersect(filtered_samples_23_sig$lsv_id, filtered_samples_123_sig$lsv_id) 
length(shared_samples_23_123_sig)


# extract filtered LSVs from the data frames above
# compare samples 1 & 2 with 1 & 3
match_samples_12_13_sig<- filtered_samples_12_sig[match(shared_samples_12_13_sig, filtered_samples_12_sig$lsv_id),]

match_samples_13_12_sig<- filtered_samples_13_sig[match(shared_samples_12_13_sig, filtered_samples_13_sig$lsv_id),]

# compare samples 1 & 2 with 2 & 3
match_samples_12_23_sig<- filtered_samples_12_sig[match(shared_samples_12_23_sig, filtered_samples_12_sig$lsv_id),]

match_samples_23_12_sig<- filtered_samples_23_sig[match(shared_samples_12_23_sig, filtered_samples_23_sig$lsv_id),]

# compare samples 1 & 2 with 1 & 2 & 3
match_samples_12_123_sig<- filtered_samples_12_sig[match(shared_samples_12_123_sig, filtered_samples_12_sig$lsv_id),]

match_samples_123_12_sig<- filtered_samples_123_sig[match(shared_samples_12_123_sig, filtered_samples_123_sig$lsv_id),]

# compare samples 1 & 3_sigwith 2 & 3
match_samples_13_23_sig<- filtered_samples_13_sig[match(shared_samples_13_23_sig, filtered_samples_13_sig$lsv_id),]

match_samples_23_13_sig<- filtered_samples_23_sig[match(shared_samples_13_23_sig, filtered_samples_23_sig$lsv_id),]

# compare samples 1 & 3_sigwith 1 & 2 & 3
match_samples_13_123_sig<- filtered_samples_13_sig[match(shared_samples_13_123_sig, filtered_samples_13_sig$lsv_id),]

match_samples_123_13_sig<- filtered_samples_123_sig[match(shared_samples_13_123_sig, filtered_samples_123_sig$lsv_id),]

# compare samples 2 & 3_sigwith 1 & 2 & 3
match_samples_23_123_sig<- filtered_samples_23_sig[match(shared_samples_23_123_sig, filtered_samples_23_sig$lsv_id),]

match_samples_123_23_sig<- filtered_samples_123_sig[match(shared_samples_23_123_sig, filtered_samples_123_sig$lsv_id),]


# extract dpsi value of the first junction for all LSVs
# deltapsi samples 1 & 2 vs samples 1 & 3
deltaPSI_samples_12_vs_13_sig = match_samples_12_13_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_13_vs_12_sig = match_samples_13_12_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 2 vs samples 2 & 3
deltaPSI_samples_12_vs_23_sig = match_samples_12_23_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_23_vs_12_sig = match_samples_23_12_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 2 vs samples 1 & 2 & 3
deltaPSI_samples_12_vs_123_sig = match_samples_12_123_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_123_vs_12_sig = match_samples_123_12_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 3 vs samples 2 & 3
deltaPSI_samples_13_vs_23_sig = match_samples_13_23_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_23_vs_13_sig = match_samples_23_13_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 1 & 3 vs samples 1 & 2 & 3
deltaPSI_samples_13_vs_123_sig = match_samples_13_123_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_123_vs_13_sig = match_samples_123_13_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

# deltapsi samples 2 & 3 vs samples 1 & 2 & 3
deltaPSI_samples_23_vs_123_sig = match_samples_23_123_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

deltaPSI_samples_123_vs_23_sig = match_samples_123_23_sig$mean_dpsi_per_lsv_junction %>%
  strsplit(split = ";") %>% 
  sapply(FUN = "[[",1) %>% as.numeric

```

```{r, warning=FALSE,message=FALSE,error=FALSE,fig.keep='all'}
# build data frame out of vectors with dpsi values 
# create scatter plot with the data frames

# correlation data frame samples 12 vs 13
correlationDataFrame_12_vs_13 <- data.frame(deltaPSI_samples_12_vs_13, deltaPSI_samples_13_vs_12)
correlationDataFrame_12_vs_13_sig <- data.frame(deltaPSI_samples_12_vs_13_sig, deltaPSI_samples_13_vs_12_sig)

sharedRegulation_scatterPlot1 = ggplot(data=correlationDataFrame_12_vs_13, aes(x=deltaPSI_samples_12_vs_13, deltaPSI_samples_13_vs_12)) +
  stat_cor(label.x.npc = .3, label.y.npc =1) +
  ggrastr::geom_point_rast(alpha=0.36, color="darkgrey") +
  geom_smooth(data=correlationDataFrame_12_vs_13, aes(x=deltaPSI_samples_12_vs_13, deltaPSI_samples_13_vs_12), method = "lm", color="darkgrey", se=FALSE) +
  ggrastr::geom_point_rast(data=correlationDataFrame_12_vs_13_sig, aes(x=deltaPSI_samples_12_vs_13_sig, y=deltaPSI_samples_13_vs_12_sig), color="black") +
  geom_smooth(data=correlationDataFrame_12_vs_13_sig, aes(x=deltaPSI_samples_12_vs_13_sig, y=deltaPSI_samples_13_vs_12_sig),method = "lm", color="black", se=FALSE) +
  geom_hline(yintercept=0, size=.5, linetype="dashed") +
  geom_vline(xintercept=0, size=.5, linetype="dashed") +
  geom_abline(xintercept=0, slope=1, linetype="dashed", size=.75, color="firebrick2") +
  coord_fixed(ratio = 1) +
  xlab("\u0394\u03A8 samples 1 & 2") +
  ylab("\u0394\u03A8 samples 1 & 3") +
  theme_bw() +
  theme(plot.title = element_text(face = "bold"))

# correlation data frame samples 12 vs 23
correlationDataFrame_12_vs_23 <- data.frame(deltaPSI_samples_12_vs_23, deltaPSI_samples_23_vs_12)
correlationDataFrame_12_vs_23_sig <- data.frame(deltaPSI_samples_12_vs_23_sig, deltaPSI_samples_23_vs_12_sig)

sharedRegulation_scatterPlot2 = ggplot(data=correlationDataFrame_12_vs_23, aes(x=deltaPSI_samples_12_vs_23, deltaPSI_samples_23_vs_12)) +
  stat_cor(label.x.npc = .3, label.y.npc =1) +
  ggrastr::geom_point_rast(alpha=0.36, color="darkgrey") +
  geom_smooth(data=correlationDataFrame_12_vs_23, aes(x=deltaPSI_samples_12_vs_23, deltaPSI_samples_23_vs_12), method = "lm", color="darkgrey", se=FALSE) +
  ggrastr::geom_point_rast(data=correlationDataFrame_12_vs_23_sig, aes(x=deltaPSI_samples_12_vs_23_sig, y=deltaPSI_samples_23_vs_12_sig), color="black") +
  geom_smooth(data=correlationDataFrame_12_vs_23_sig, aes(x=deltaPSI_samples_12_vs_23_sig, y=deltaPSI_samples_23_vs_12_sig),method = "lm", color="black", se=FALSE) +
  geom_hline(yintercept=0, size=.5, linetype="dashed") +
  geom_vline(xintercept=0, size=.5, linetype="dashed") +
  geom_abline(xintercept=0, slope=1, linetype="dashed", size=.75, color="firebrick2") +
  coord_fixed(ratio = 1) +
  xlab("\u0394\u03A8 samples 1 & 2") +
  ylab("\u0394\u03A8 samples 2 & 3") +
  theme_bw() +
  theme(plot.title = element_text(face = "bold"))

# correlation data frame samples 12 vs 123
correlationDataFrame_12_vs_123 <- data.frame(deltaPSI_samples_12_vs_123, deltaPSI_samples_123_vs_12)
correlationDataFrame_12_vs_123_sig <- data.frame(deltaPSI_samples_12_vs_123_sig, deltaPSI_samples_123_vs_12_sig)

sharedRegulation_scatterPlot3 = ggplot(data=correlationDataFrame_12_vs_123, aes(x=deltaPSI_samples_12_vs_123, deltaPSI_samples_123_vs_12)) +
  stat_cor(label.x.npc = .3, label.y.npc =1) +
  ggrastr::geom_point_rast(alpha=0.36, color="darkgrey", size=0.3) +
  geom_smooth(data=correlationDataFrame_12_vs_123, aes(x=deltaPSI_samples_12_vs_123, deltaPSI_samples_123_vs_12), method = "lm", color="darkgrey", se=FALSE) +
  ggrastr::geom_point_rast(data=correlationDataFrame_12_vs_123_sig, aes(x=deltaPSI_samples_12_vs_123_sig, y=deltaPSI_samples_123_vs_12_sig), color="black", size=0.3) +
  geom_smooth(data=correlationDataFrame_12_vs_123_sig, aes(x=deltaPSI_samples_12_vs_123_sig, y=deltaPSI_samples_123_vs_12_sig),method = "lm", color="black") +
  geom_hline(yintercept=0, size=.5, linetype="dashed") +
  geom_vline(xintercept=0, size=.5, linetype="dashed") +
  geom_abline(xintercept=0, slope=1, linetype="dashed", size=.75, color="firebrick2") +
  coord_cartesian(xlim = c(-1, 1), ylim = c(-1, 1)) +
  xlab("dPSI samples 1 & 2") +
  ylab("dPSI samples 1 & 2 & 3") +
  theme_bw() +
  theme(aspect.ratio=1) +
  theme(plot.title = element_text(face = "bold")) +
  ggtitle("F")

# correlation data frame samples 13 vs 23
correlationDataFrame_13_vs_23 <- data.frame(deltaPSI_samples_13_vs_23, deltaPSI_samples_23_vs_13)
correlationDataFrame_13_vs_23_sig <- data.frame(deltaPSI_samples_13_vs_23_sig, deltaPSI_samples_23_vs_13_sig)

sharedRegulation_scatterPlot4 = ggplot(data=correlationDataFrame_13_vs_23, aes(x=deltaPSI_samples_13_vs_23, deltaPSI_samples_23_vs_13)) +
  stat_cor(label.x.npc = .3, label.y.npc =1) +
  ggrastr::geom_point_rast(alpha=0.36, color="darkgrey") +
  geom_smooth(data=correlationDataFrame_13_vs_23, aes(x=deltaPSI_samples_13_vs_23, deltaPSI_samples_23_vs_13), method = "lm", color="darkgrey", se=FALSE) +
  ggrastr::geom_point_rast(data=correlationDataFrame_13_vs_23_sig, aes(x=deltaPSI_samples_13_vs_23_sig, y=deltaPSI_samples_23_vs_13_sig), color="black") +
  geom_smooth(data=correlationDataFrame_13_vs_23_sig, aes(x=deltaPSI_samples_13_vs_23_sig, y=deltaPSI_samples_23_vs_13_sig),method = "lm", color="black", se=FALSE) +
  geom_hline(yintercept=0, size=.5, linetype="dashed") +
  geom_vline(xintercept=0, size=.5, linetype="dashed") +
  geom_abline(xintercept=0, slope=1, linetype="dashed", size=.75, color="firebrick2") +
  coord_fixed(ratio = 1) +
  xlab("\u0394\u03A8 samples 1 & 3") +
  ylab("\u0394\u03A8 samples 2 & 3") +
  theme_bw() +
  theme(plot.title = element_text(face = "bold"))

# correlation data frame samples 13 vs 123
correlationDataFrame_13_vs_123 <- data.frame(deltaPSI_samples_13_vs_123, deltaPSI_samples_123_vs_13)
correlationDataFrame_13_vs_123_sig <- data.frame(deltaPSI_samples_13_vs_123_sig, deltaPSI_samples_123_vs_13_sig)

sharedRegulation_scatterPlot5 = ggplot(data=correlationDataFrame_13_vs_123, aes(x=deltaPSI_samples_13_vs_123, deltaPSI_samples_123_vs_13)) +
  stat_cor(label.x.npc = .3, label.y.npc =1) +
  ggrastr::geom_point_rast(alpha=0.36, color="darkgrey") +
  geom_smooth(data=correlationDataFrame_13_vs_123, aes(x=deltaPSI_samples_13_vs_123, deltaPSI_samples_123_vs_13), method = "lm", color="darkgrey", se=FALSE) +
  ggrastr::geom_point_rast(data=correlationDataFrame_13_vs_123_sig, aes(x=deltaPSI_samples_13_vs_123_sig, y=deltaPSI_samples_123_vs_13_sig), color="black") +
  geom_smooth(data=correlationDataFrame_13_vs_123_sig, aes(x=deltaPSI_samples_13_vs_123_sig, y=deltaPSI_samples_123_vs_13_sig),method = "lm", color="black", se=FALSE) +
  geom_hline(yintercept=0, size=.5, linetype="dashed") +
  geom_vline(xintercept=0, size=.5, linetype="dashed") +
  geom_abline(xintercept=0, slope=1, linetype="dashed", size=.75, color="firebrick2") +
  coord_fixed(ratio = 1) +
  xlab("\u0394\u03A8 samples 1 & 3") +
  ylab("\u0394\u03A8 samples 1 & 2 & 3") +
  theme_bw() +
  theme(plot.title = element_text(face = "bold"))

# correlation data frame samples 23 vs 123
correlationDataFrame_23_vs_123 <- data.frame(deltaPSI_samples_23_vs_123, deltaPSI_samples_123_vs_23)
correlationDataFrame_23_vs_123_sig <- data.frame(deltaPSI_samples_23_vs_123_sig, deltaPSI_samples_123_vs_23_sig)

sharedRegulation_scatterPlot6 = ggplot(data=correlationDataFrame_23_vs_123, aes(x=deltaPSI_samples_23_vs_123, deltaPSI_samples_123_vs_23)) +
  stat_cor(label.x.npc = .3, label.y.npc =1) +
  ggrastr::geom_point_rast(alpha=0.36, color="darkgrey") +
  geom_smooth(data=correlationDataFrame_23_vs_123, aes(x=deltaPSI_samples_23_vs_123, deltaPSI_samples_123_vs_23), method = "lm", color="darkgrey", se=FALSE) +
  ggrastr::geom_point_rast(data=correlationDataFrame_23_vs_123_sig, aes(x=deltaPSI_samples_23_vs_123_sig, y=deltaPSI_samples_123_vs_23_sig), color="black") +
  geom_smooth(data=correlationDataFrame_23_vs_123_sig, aes(x=deltaPSI_samples_23_vs_123_sig, y=deltaPSI_samples_123_vs_23_sig),method = "lm", color="black", se=FALSE) +
  geom_hline(yintercept=0, size=.5, linetype="dashed") +
  geom_vline(xintercept=0, size=.5, linetype="dashed") +
  geom_abline(xintercept=0, slope=1, linetype="dashed", size=.75, color="firebrick2") +
  coord_fixed(ratio = 1) +
  xlab("\u0394\u03A8 samples 2 & 3") +
  ylab("\u0394\u03A8 samples 1 & 2 & 3") +
  theme_bw() +
  theme(plot.title = element_text(face = "bold"))

sharedRegulation_scatterPlot1
sharedRegulation_scatterPlot2
sharedRegulation_scatterPlot3
sharedRegulation_scatterPlot4
sharedRegulation_scatterPlot5
sharedRegulation_scatterPlot6

'# save ggplots
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/sharedRehulation_100_75.pdf", plot = U2AF2_sharedRegulation_scatterPlot1)
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/sharedRehulation_100_50.pdf", plot = U2AF2_sharedRegulation_scatterPlot2)
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/sharedRehulation_100_36.pdf", plot = U2AF2_sharedRegulation_scatterPlot3)
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/sharedRehulation_75_50.pdf", plot = U2AF2_sharedRegulation_scatterPlot4)
ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/sharedRehulation_50_36.pdf", plot = U2AF2_sharedRegulation_scatterPlot5)'

ggsave(filename = "C:/Users/ladwi/Desktop/HiWi/project_impact_read_length/plots/sharedRegulation_samples_12_vs_123_sampleSize.pdf", plot = sharedRegulation_scatterPlot3, width = 5, height = 5, units = "cm")

```




